server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期（传递给前端）
    session:
      cookie:
        max-age: 2592000
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  profiles:
    active: local
  application:
    name: long-picture
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lone_picture
    username: root
    password: 123456
  #redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  # session配置
  session:
    store-type: redis
    # session 30 天后过期
    timeout: 2592000
  # 空间图片分表
  shardingsphere:
    datasource:
      names: lone_picture
      lone_picture:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/lone_picture
        username: root
        password: 123456
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: lone_picture.picture  # 动态分表
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.lone.lonepicturebackend.manager.sharding.PictureShardingAlgorithm
    props:
      sql-show: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-not-delete-value: 0
      logic-delete-value: 1
    enable-sql-runner: true

knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.lone.lonepicturebackend.controller
